import type { MetadataRoute } from "next";

export const dynamic = "force-static";

const siteUrl = process.env.WEB_URL ?? process.env.NEXT_PUBLIC_WEB_URL ?? "https://homeopathypharma.com";

/** Static export sitemap seed — full segmented sitemaps are generated by the API/worker later. */
export default function sitemap(): MetadataRoute.Sitemap {
  const paths = [
    "/",
    "/search/",
    "/cart/",
    "/doctors/",
    "/health/",
    "/pets/",
    "/legal/privacy/",
    "/legal/terms/",
    "/legal/disclaimer/",
    "/products/arnica-montana-30c/",
    "/doctors/sample-practitioner/",
    "/health/body-systems/cardiovascular-system/",
    "/pets/dogs/",
    "/pets/cats/",
  ];

  return paths.map((path) => ({
    url: `${siteUrl}${path}`,
    changeFrequency: path === "/" ? "daily" : "weekly",
    priority: path === "/" ? 1 : 0.7,
  }));
}
