import type { MetadataRoute } from "next";

export const dynamic = "force-static";

const siteUrl = process.env.WEB_URL ?? process.env.NEXT_PUBLIC_WEB_URL ?? "https://homeopathypharma.com";

/** Static export sitemap seed — full segmented sitemaps are generated by the API/worker later. */
export default function sitemap(): MetadataRoute.Sitemap {
  const paths = [
    "/",
    "/about/",
    "/contact/",
    "/faq/",
    "/how-it-works/",
    "/shop/",
    "/shop/categories/",
    "/shop/brands/",
    "/shop/bundles/",
    "/shop/offers/",
    "/shop/new-arrivals/",
    "/shop/bestsellers/",
    "/shop/doctor-recommended/",
    "/consult/",
    "/consult/online/",
    "/consult/offline/",
    "/doctors/",
    "/doctors/city/mumbai/",
    "/doctors/city/delhi/",
    "/doctors/city/bengaluru/",
    "/health/",
    "/health/symptoms/",
    "/health/age-groups/",
    "/health/gender-health/",
    "/health/lifestyle/",
    "/health/faq/",
    "/health/body/",
    "/pets/",
    "/pets/pet-doctors/",
    "/pets/pet-consultation/",
    "/blog/",
    "/guides/",
    "/research/",
    "/sources/",
    "/editorial-policy/",
    "/medical-review-policy/",
    "/content-update-log/",
    "/brands/",
    "/manufacturers/",
    "/doctor-verification/",
    "/track-order/",
    "/serviceability/",
    "/search/",
    "/privacy-policy/",
    "/terms/",
    "/medical-disclaimer/",
    "/shipping-policy/",
    "/return-policy/",
    "/refund-policy/",
    "/legal/privacy/",
    "/legal/terms/",
    "/legal/disclaimer/",
    "/products/arnica-montana-30c/",
    "/doctors/sample-practitioner/",
    "/health/body-systems/cardiovascular-system/",
    "/pets/dogs/",
    "/pets/cats/",
  ];

  return paths.map((path) => ({
    url: `${siteUrl}${path}`,
    changeFrequency: path === "/" ? "daily" : "weekly",
    priority: path === "/" ? 1 : 0.7,
  }));
}
