import {
  COMMON_FAQS,
  type ProductSeed,
  type WhatsIncludedRich,
} from "./seed-helpers";

export interface CategorySeed {
  name: string;
  slug: string;
  description: string;
  sortOrder: number;
}

export type { ProductSeed, WhatsIncludedRich };

export const CATEGORY_SEEDS: CategorySeed[] = [
  {
    name: "Kundali & Birth Charts",
    slug: "kundali",
    description: "Janam Kundali, houses, dasha timelines, and natal chart deep-dives.",
    sortOrder: 1,
  },
  {
    name: "Marriage & Matching",
    slug: "marriage",
    description: "Guna Milan, love compatibility, marriage timing, and couple synastry.",
    sortOrder: 2,
  },
  {
    name: "Career & Profession",
    slug: "career",
    description: "Career path, timing windows, business themes, and foreign-work motifs.",
    sortOrder: 3,
  },
  {
    name: "Wealth & Family",
    slug: "wealth",
    description: "Prosperity themes, property symbolism, education, and family dynamics.",
    sortOrder: 4,
  },
  {
    name: "Dosha & Planets",
    slug: "dosha",
    description: "Dosha scans, Manglik, Rahu-Ketu, Sade Sati, and planet spotlights.",
    sortOrder: 5,
  },
  {
    name: "Face Self-Discovery",
    slug: "self-discovery",
    description: "AI face reading and personality self-reflection reports.",
    sortOrder: 6,
  },
  {
    name: "Numerology",
    slug: "numerology",
    description: "Name, mobile, personal year, and complete numerology profiles.",
    sortOrder: 7,
  },
  {
    name: "Horoscopes & Transits",
    slug: "daily-astrology",
    description: "Year-ahead forecasts, gochar (transit) reports, and monthly guidance.",
    sortOrder: 8,
  },
];

function pack(
  included: string[],
  chapters: string[],
  whoFor: string[],
  outcomes: string[],
  pageEstimate?: number,
): WhatsIncludedRich {
  return { included, chapters, whoFor, outcomes, pageEstimate };
}

/**
 * Unique catalogue — no near-duplicate SKUs.
 * Inspired by how major astrology brands structure PDPs: long “what you get”,
 * chapter lists, who-it’s-for, delivery, and honest FAQs.
 */
export const PRODUCT_SEEDS: ProductSeed[] = [
  // ── Kundali ─────────────────────────────────────────────
  {
    name: "Complete Janam Kundali",
    slug: "janam-kundali",
    categorySlug: "kundali",
    shortDescription: "Your full birth-chart PDF: planets, houses, dasha overview, and life-theme chapters.",
    description:
      "The Complete Janam Kundali is our flagship natal report — the single report most people start with. Inspired by how leading Vedic platforms present birth charts, this PDF walks you through Lagna, Moon, planetary placements, the twelve houses, and a clear Vimshottari dasha overview so you can see the story of your chart in one place.\n\nYou receive interpretive guidance written for reflection and entertainment, with plain-language explanations of traditional terms. Use it to understand temperament themes, relationship motifs, career colour, and timing chapters — then decide which specialised reports to explore next.\n\nIdeal as a gift for family members or as your personal reference before marriage matching, career timing, or dosha deep-dives.",
    whatsIncluded: pack(
      [
        "North-Indian style chart snapshot with Lagna highlighted",
        "Planet-by-planet placement table (sign, house, nakshatra theme)",
        "Twelve-house life-theme walkthrough",
        "Vimshottari Mahadasha overview with current period callout",
        "Personality & temperament chapter from Lagna + Moon",
        "Relationship & career motif highlights",
        "Plain-language glossary for key Jyotish terms",
        "Digital PDF + dashboard archive access",
        "Clear entertainment / non-advice disclaimer on every report",
      ],
      [
        "1. Chart overview & how to read this report",
        "2. Lagna & rising-sign temperament",
        "3. Moon, mind & emotional rhythm",
        "4. Planetary portraits (Sun through Ketu)",
        "5. House-by-house life map",
        "6. Dasha timeline snapshot",
        "7. Reflection prompts & next-step report suggestions",
      ],
      [
        "Anyone new to Vedic astrology who wants one complete starting PDF",
        "Parents creating a keepsake chart for a child",
        "Couples who want a shared baseline before matching reports",
        "Readers who prefer structured chapters over short rashifal blurbs",
      ],
      [
        "A shareable PDF you can revisit anytime",
        "Clarity on which specialised report to buy next",
        "Vocabulary to discuss your chart with family thoughtfully",
      ],
    ),
    faqs: [
      ...COMMON_FAQS,
      {
        q: "How is this different from smaller Kundali reports?",
        a: "This is the all-in-one natal PDF. Specialised reports (Navamsa, Mahadasha deep-dive, Dosha scan) go deeper on one topic; Janam Kundali gives the full map first.",
      },
      {
        q: "How many pages should I expect?",
        a: "Typically 18–28 pages depending on your placements and how many interpretive notes apply. Page count is an estimate, not a guarantee.",
      },
    ],
    deliveryNote: "PDF usually ready within a few minutes after payment. Check your dashboard and email.",
    reportTemplateKey: "janam-kundali",
    sortOrder: 1,
    pageEstimate: 24,
  },
  {
    name: "Lagna Personality Report",
    slug: "lagna-analysis",
    categorySlug: "kundali",
    shortDescription: "Ascendant-focused temperament, first impressions, and body–mind style themes.",
    description:
      "Your Lagna (Ascendant) sets the tone for how life approaches you and how you meet the world. This report focuses only on rising-sign themes, Lagna lord placement, and the personality colour of your 1st house — without repeating a full Janam Kundali.\n\nExpect a deep dive into presence, vitality motifs, decision style, and how others may first experience you. Perfect when you already have a birth chart and want personality clarity.",
    whatsIncluded: pack(
      [
        "Rising-sign portrait with elemental & modality notes",
        "Lagna lord placement & aspect themes",
        "1st-house story: vitality, identity, presentation",
        "Strengths & growth edges for self-awareness",
        "How Lagna colours career & relationship first impressions",
        "Reflection journal prompts",
        "Digital PDF delivery",
      ],
      [
        "1. What Lagna means in plain language",
        "2. Your rising-sign portrait",
        "3. Lagna lord journey",
        "4. Body–mind style themes",
        "5. Social first impressions",
        "6. Practical reflection exercises",
      ],
      ["Readers who want personality focus", "Coaches/journalers using chart symbolism", "Anyone with an existing full Kundali"],
      ["Clearer self-description language", "Insight into presence & first impressions"],
    ),
    faqs: COMMON_FAQS,
    deliveryNote: "PDF delivered digitally within minutes after payment.",
    reportTemplateKey: "lagna-analysis",
    sortOrder: 2,
    pageEstimate: 12,
  },
  {
    name: "Moon & Nakshatra Report",
    slug: "nakshatra-analysis",
    categorySlug: "kundali",
    shortDescription: "Birth-star and Moon-sign storytelling for moods, instincts, and inner rhythm.",
    description:
      "Nakshatra (birth star) and Chandra Rashi shape emotional habits, comfort needs, and symbolic life motifs. This report centres the Moon — not a repeat of the full Kundali — with nakshatra deity themes, pada colour, and daily-rhythm notes for reflective journaling.",
    whatsIncluded: pack(
      [
        "Moon sign & house themes",
        "Birth nakshatra meaning & symbolic motifs",
        "Pada / quarter colour notes",
        "Emotional needs & comfort patterns",
        "Relationship nurture style from the Moon",
        "Gentle routine & reflection suggestions",
        "PDF + dashboard copy",
      ],
      [
        "1. Moon as mind in Vedic storytelling",
        "2. Your Chandra Rashi portrait",
        "3. Nakshatra deep-dive",
        "4. Inner needs vs outer persona",
        "5. Care & rhythm suggestions",
      ],
      ["People curious about birth-star meaning", "Anyone seeking emotional self-awareness", "Parents exploring a child’s Moon themes"],
      ["Language for moods & needs", "Nakshatra-based reflection prompts"],
    ),
    faqs: COMMON_FAQS,
    deliveryNote: "Instant digital PDF after payment confirmation.",
    reportTemplateKey: "nakshatra-analysis",
    sortOrder: 3,
    pageEstimate: 14,
  },
  {
    name: "Navamsa (D9) Partnership Chart",
    slug: "navamsa-chart",
    categorySlug: "kundali",
    shortDescription: "Divisional D9 chart notes on dharma, partnership quality, and inner maturity themes.",
    description:
      "Navamsa (D9) is the classic divisional chart used in Vedic tradition to refine partnership and dharma themes. This report explains your D9 Lagna, key planetary shifts from the Rasi chart, and how tradition reads long-term bond colour — clearly framed as symbolic guidance, not a marriage guarantee.",
    whatsIncluded: pack(
      [
        "D9 chart snapshot vs Rasi comparison notes",
        "Navamsa Lagna & lord themes",
        "Venus / 7th-house refinement in D9",
        "Dharma & inner-maturity chapter",
        "How to use D9 alongside Guna Milan (not instead of it)",
        "PDF report with glossary",
      ],
      [
        "1. Why Navamsa matters",
        "2. Your D9 overview",
        "3. Partnership colour in D9",
        "4. Dharma & growth reading",
        "5. Combining with matching reports",
      ],
      ["Engaged couples preparing thoughtfully", "Students of Vedic astrology", "Anyone past the basic Janam Kundali"],
      ["Clearer D9 literacy", "Partnership themes for discussion"],
    ),
    faqs: COMMON_FAQS,
    deliveryNote: "PDF ready in your dashboard shortly after payment.",
    reportTemplateKey: "navamsa-chart",
    sortOrder: 4,
    pageEstimate: 16,
  },
  {
    name: "Mahadasha Timeline Report",
    slug: "mahadasha-antardasha",
    categorySlug: "kundali",
    shortDescription: "Vimshottari Mahadasha & Antardasha chapters with symbolic timing windows.",
    description:
      "Dasha periods describe symbolic life chapters. This timeline report maps your current and upcoming Mahadasha/Antardasha spans with interpretive themes for career, relationships, learning, and rest — never as fixed predictions. Designed like premium timing PDFs on major astrology sites: long enough to plan reflections, clear enough to share with family.",
    whatsIncluded: pack(
      [
        "Full Vimshottari sequence relevant to your birth data",
        "Current Mahadasha deep-dive",
        "Antardasha breakdown for the active period",
        "Upcoming chapter previews (next major shifts)",
        "Theme tags: work, bonds, learning, health-of-routine",
        "Calendar-style timeline graphic in PDF",
        "Reflection checklist for each chapter",
      ],
      [
        "1. How dasha storytelling works",
        "2. Your lifetime dasha map",
        "3. Current period in detail",
        "4. Near-term Antardasha colour",
        "5. Planning prompts (non-predictive)",
      ],
      ["People deciding when to focus energy", "Anyone in a noticeable life transition", "Readers who already know their chart basics"],
      ["A dated timeline you can revisit", "Language for “what chapter am I in?”"],
    ),
    faqs: COMMON_FAQS,
    deliveryNote: "Digital delivery within minutes; timeline uses your birth details.",
    reportTemplateKey: "mahadasha-antardasha",
    sortOrder: 5,
    pageEstimate: 20,
  },
  {
    name: "Twelve Houses Life Map",
    slug: "house-analysis",
    categorySlug: "kundali",
    shortDescription: "House-by-house walkthrough of life themes from self to spirituality.",
    description:
      "Each bhava (house) frames a life domain — self, wealth motifs, communication, home, creativity, service, partnership, transformation, belief, vocation, networks, and release. This Life Map gives one dedicated chapter per house with planetary occupancy notes, without duplicating planet-only or dasha-only reports.",
    whatsIncluded: pack(
      [
        "All 12 houses explained in everyday language",
        "Occupying & aspecting planet notes per house",
        "Strength / emphasis callouts where relevant",
        "Cross-links to career, marriage, and wealth motifs",
        "Blank reflection lines in the PDF",
        "Dashboard archive access",
      ],
      [
        "1. How to use a house map",
        "2–13. Houses 1 through 12 (one chapter each)",
        "14. Synthesis: your loudest houses",
      ],
      ["Visual learners who like structured domains", "People comparing family charts", "Students building chart literacy"],
      ["A reference map for years of journaling", "Clearer “which house is loud?” awareness"],
    ),
    faqs: COMMON_FAQS,
    deliveryNote: "PDF delivered after payment to email + dashboard.",
    reportTemplateKey: "house-analysis",
    sortOrder: 6,
    pageEstimate: 22,
  },

  // ── Marriage ────────────────────────────────────────────
  {
    name: "Kundali Matching (Guna Milan)",
    slug: "guna-milan",
    categorySlug: "marriage",
    shortDescription: "Traditional Ashtakoot Guna Milan score with plain-language compatibility notes.",
    description:
      "Kundali Matching is the classic family-facing compatibility report. You get Ashtakoot Guna Milan scoring presented the way major match-making platforms do — with each koot explained, Manglik flag context, and calm language for family discussions.\n\nRequires birth details for both partners. This report focuses on traditional matching points; for romantic chemistry storytelling see Love Compatibility, and for timing see Marriage Timing Windows.",
    whatsIncluded: pack(
      [
        "Ashtakoot score table (out of 36) with koot-by-koot notes",
        "Varna, Vashya, Tara, Yoni, Graha Maitri, Gana, Bhakoot, Nadi explained",
        "Manglik presence check for both charts (informational)",
        "Family discussion summary page",
        "What a score does and does not mean",
        "Suggestions for complementary reports",
        "Dual-chart PDF package",
      ],
      [
        "1. How Guna Milan works",
        "2. Partner A & B chart snapshots",
        "3. Koot-by-koot results",
        "4. Manglik context page",
        "5. Conversation guide for families",
      ],
      ["Families evaluating a match traditionally", "Couples who want a shared matching PDF", "Anyone comparing multiple prospects thoughtfully"],
      ["A clear scorecard with explanations", "Calmer language for sensitive talks"],
    ),
    faqs: [
      ...COMMON_FAQS,
      {
        q: "Do you need both birth times?",
        a: "Yes for best accuracy. If one time is unknown, matching still runs with noted limitations on time-sensitive flags.",
      },
      {
        q: "Does a low score mean we should not marry?",
        a: "No. Scores are traditional symbolic tools. Many couples with varied scores build healthy relationships. Use this for reflection, not as a verdict.",
      },
    ],
    deliveryNote: "PDF for both partners delivered together after payment.",
    reportTemplateKey: "guna-milan",
    sortOrder: 1,
    pageEstimate: 18,
  },
  {
    name: "Love Compatibility Report",
    slug: "love-compatibility",
    categorySlug: "marriage",
    shortDescription: "Romantic chemistry themes — attraction, communication, and emotional fit.",
    description:
      "Distinct from Guna Milan: this report explores romantic chemistry, Venus/Mars motifs, Moon harmony, and communication style between two people. Written for dating and early-relationship reflection — not a replacement for traditional matching if families need Ashtakoot.",
    whatsIncluded: pack(
      [
        "Synastry-style attraction chapter",
        "Emotional needs comparison (Moon themes)",
        "Communication & conflict-style notes",
        "Affection language (Venus motifs)",
        "Shared growth edges",
        "Couple reflection questions",
        "PDF for both partners",
      ],
      [
        "1. Chemistry vs traditional matching",
        "2. Attraction & spark themes",
        "3. Emotional safety & nurture",
        "4. Talk & repair styles",
        "5. Growing together prompts",
      ],
      ["Dating couples", "Partners curious about chemistry symbolism", "People who already completed Guna Milan"],
      ["Shared vocabulary for love styles", "Honest growth conversations"],
    ),
    faqs: COMMON_FAQS,
    deliveryNote: "Couple PDF delivered digitally after payment.",
    reportTemplateKey: "love-compatibility",
    sortOrder: 2,
    pageEstimate: 16,
  },
  {
    name: "Marriage Timing Windows",
    slug: "marriage-timing",
    categorySlug: "marriage",
    shortDescription: "Dasha and transit windows framed as possible wedding-chapter markers.",
    description:
      "Marriage Timing Windows highlights symbolic periods that traditional astrology associates with partnership milestones. You receive dated ranges with interpretive colour — never a promised wedding date. Pair with Guna Milan for match quality, and Navamsa for partnership depth.",
    whatsIncluded: pack(
      [
        "Current dasha colour for relationship themes",
        "Upcoming windows across the next several years",
        "Transit highlights often watched for marriage (interpretive)",
        "Personal readiness reflection checklist",
        "Family planning conversation page",
        "PDF timeline",
      ],
      [
        "1. Timing vs destiny — our honest framing",
        "2. Your relationship dasha climate",
        "3. Window map",
        "4. How to use windows thoughtfully",
      ],
      ["People considering engagement timelines", "Families planning ceremonies", "Anyone pairing timing with matching"],
      ["Dated reflection windows", "Less anxiety around “when” questions"],
    ),
    faqs: COMMON_FAQS,
    deliveryNote: "Timeline PDF in dashboard within minutes.",
    reportTemplateKey: "marriage-timing",
    sortOrder: 3,
    pageEstimate: 14,
  },
  {
    name: "Couple Synastry Report",
    slug: "couple-kundali",
    categorySlug: "marriage",
    shortDescription: "Side-by-side couple chart: strengths, friction points, and shared growth path.",
    description:
      "A full couple package combining chart comparison, house overlays, and practical relationship chapters. Different from score-only Guna Milan and chemistry-only Love Compatibility — this is the long-form “how we function together” report families and couples keep as a reference.",
    whatsIncluded: pack(
      [
        "Side-by-side chart snapshots",
        "Composite theme summary",
        "Strengths you amplify in each other",
        "Friction points & repair suggestions (reflective)",
        "Shared values & lifestyle motifs",
        "Long-term growth roadmap chapter",
        "Printable couple PDF",
      ],
      [
        "1. How to read a couple report",
        "2. Individual snapshots",
        "3. Overlap & harmony zones",
        "4. Growth & friction",
        "5. Shared roadmap",
      ],
      ["Engaged or married couples", "Partners wanting one comprehensive PDF", "Gift for anniversaries"],
      ["A shared relationship reference", "Kinder conflict language"],
    ),
    faqs: COMMON_FAQS,
    deliveryNote: "Combined couple PDF after payment.",
    reportTemplateKey: "couple-kundali",
    sortOrder: 4,
    pageEstimate: 22,
  },

  // ── Career ──────────────────────────────────────────────
  {
    name: "Career Path Analysis",
    slug: "career-analysis",
    categorySlug: "career",
    shortDescription: "10th-house vocation themes, work style, and professional identity motifs.",
    description:
      "Career Path Analysis focuses on vocation symbolism: 10th house, karma motifs, skill colour from Mercury/Mars/Sun, and work-environment fit. It does not promise promotions or job offers — it helps you reflect on strengths and directions the way leading career-astrology PDPs structure long guidance chapters.",
    whatsIncluded: pack(
      [
        "10th-house & Midheaven-style vocation notes",
        "Work-style portrait (pace, leadership, collaboration)",
        "Skill & interest motif clusters",
        "Environment fit (corporate, creative, service, solo)",
        "Blind spots & growth edges at work",
        "90-day reflection plan",
        "PDF report",
      ],
      [
        "1. Chart & career — honest limits",
        "2. Your vocation signature",
        "3. Strength clusters",
        "4. Environment fit",
        "5. Actionable reflection plan",
      ],
      ["Students choosing fields", "Professionals feeling stuck", "Career changers seeking symbolic clarity"],
      ["Clearer role-fit language", "A plan for experiments, not guarantees"],
    ),
    faqs: COMMON_FAQS,
    deliveryNote: "Career PDF delivered digitally post-payment.",
    reportTemplateKey: "career-analysis",
    sortOrder: 1,
    pageEstimate: 16,
  },
  {
    name: "Career Timing Report",
    slug: "career-timing",
    categorySlug: "career",
    shortDescription: "Dasha chapters that may feel more supportive for career moves and skill bets.",
    description:
      "Separate from Career Path: this report is about when chapters may feel more supportive for applications, launches, studies, or rest — using dasha/transit storytelling. Use Path for “what”, Timing for “when to focus.”",
    whatsIncluded: pack(
      [
        "Current career-coloured dasha climate",
        "Upcoming windows for effort vs consolidation",
        "Skill-building period notes",
        "Caution/rest markers (symbolic)",
        "Timeline PDF graphic",
      ],
      [
        "1. Timing without pressure",
        "2. Present climate",
        "3. Forward windows",
        "4. How to schedule experiments",
      ],
      ["Job seekers", "Founders planning launches", "Anyone pairing with Career Path Analysis"],
      ["A calendar of focus themes", "Permission to rest in quieter chapters"],
    ),
    faqs: COMMON_FAQS,
    deliveryNote: "Timing PDF in dashboard after payment.",
    reportTemplateKey: "career-timing",
    sortOrder: 2,
    pageEstimate: 12,
  },
  {
    name: "Business & Startup Themes",
    slug: "business-kundali",
    categorySlug: "career",
    shortDescription: "Entrepreneurial chart motifs for founders and side-hustle planners.",
    description:
      "Built for founders: risk appetite symbolism, partnership-in-business motifs, visibility (Sun), negotiation (Mercury), and persistence (Saturn). Not financial, legal, or fundraising advice — reflective storytelling for builders.",
    whatsIncluded: pack(
      [
        "Founder temperament portrait",
        "Solo vs co-founder fit themes",
        "Visibility & branding motifs",
        "Cashflow attitude symbolism (not investment advice)",
        "Resilience & burnout watchouts",
        "Quarterly founder reflection sheet",
      ],
      [
        "1. Chart as co-founder metaphor",
        "2. Builder strengths",
        "3. Partnership & team",
        "4. Pace & perseverance",
        "5. Reflection sheet",
      ],
      ["Startup founders", "Freelancers going full-time", "Family-business next gens"],
      ["Clearer founder self-knowledge", "Better co-founder conversations"],
    ),
    faqs: COMMON_FAQS,
    deliveryNote: "Business themes PDF after payment.",
    reportTemplateKey: "business-kundali",
    sortOrder: 3,
    pageEstimate: 15,
  },
  {
    name: "Foreign Career Themes",
    slug: "foreign-career-analysis",
    categorySlug: "career",
    shortDescription: "Abroad-work and relocation motifs from chart travel indicators.",
    description:
      "Explores symbolic indicators traditionally linked with work or study away from birth place. Explicitly not immigration, visa, or legal advice — a reflective report for people curious about overseas chapters.",
    whatsIncluded: pack(
      [
        "Travel & relocation motifs from chart",
        "Work-abroad vs settle-abroad distinction (symbolic)",
        "Adaptation & homesickness themes",
        "Timing colour for exploration windows",
        "Practical reflection checklist before big moves",
      ],
      [
        "1. What this report is not (legal disclaimer)",
        "2. Abroad indicators in your chart",
        "3. Work vs settle themes",
        "4. Emotional adaptation",
        "5. Decision checklist",
      ],
      ["Students eyeing overseas study", "Professionals considering transfers", "Families discussing relocation"],
      ["Structured questions before a move", "Symbolic framing for family talks"],
    ),
    faqs: COMMON_FAQS,
    deliveryNote: "PDF delivered digitally after payment.",
    reportTemplateKey: "foreign-career-analysis",
    sortOrder: 4,
    pageEstimate: 13,
  },

  // ── Wealth & Family ─────────────────────────────────────
  {
    name: "Wealth & Prosperity Themes",
    slug: "wealth-analysis",
    categorySlug: "wealth",
    shortDescription: "2nd & 11th house money motifs for reflective financial curiosity.",
    description:
      "Wealth themes from traditional houses of resources and gains — attitude to money, earning style, and generosity patterns. Not stock tips, tax advice, or guaranteed gains. Structured like premium finance-astrology PDFs: long chapters, clear disclaimers, actionable reflection only.",
    whatsIncluded: pack(
      [
        "2nd & 11th house storytelling",
        "Earning style & resource attitude",
        "Spending / saving temperament motifs",
        "Collaboration & income-network themes",
        "Gratitude & generosity chapter",
        "Money-mindset journal prompts",
      ],
      [
        "1. Astrology is not financial advice",
        "2. Resource signature",
        "3. Gains & networks",
        "4. Habits & values",
        "5. Reflection plan",
      ],
      ["Anyone curious about money psychology via chart", "Families discussing values", "Readers who already have Janam Kundali"],
      ["Healthier money conversations", "Values-aligned habit experiments"],
    ),
    faqs: COMMON_FAQS,
    deliveryNote: "Wealth themes PDF after payment.",
    reportTemplateKey: "wealth-analysis",
    sortOrder: 1,
    pageEstimate: 14,
  },
  {
    name: "Property & Home Themes",
    slug: "property-analysis",
    categorySlug: "wealth",
    shortDescription: "Home, land, and living-space symbolism from chart houses and transits.",
    description:
      "Focuses on 4th-house home motifs and property-related symbolism. Helpful for reflecting on living environment needs — not a real-estate investment recommendation.",
    whatsIncluded: pack(
      [
        "4th-house home & roots portrait",
        "Comfort vs status in living spaces",
        "Family property conversation prompts",
        "Relocation-at-home themes",
        "PDF with checklist before big housing decisions",
      ],
      [
        "1. Home as chart metaphor",
        "2. Your nesting signature",
        "3. Change & stability motifs",
        "4. Family discussion sheet",
      ],
      ["People planning a home change", "Joint families aligning expectations"],
      ["Clearer home priorities", "Calmer property talks"],
    ),
    faqs: COMMON_FAQS,
    deliveryNote: "Digital PDF shortly after payment.",
    reportTemplateKey: "property-analysis",
    sortOrder: 2,
    pageEstimate: 11,
  },
  {
    name: "Education & Learning Style",
    slug: "education-analysis",
    categorySlug: "wealth",
    shortDescription: "Study motivation, learning style, and education-path motifs from the chart.",
    description:
      "5th/9th house learning themes: curiosity style, exam stress patterns (symbolic), mentor attraction, and fields that may feel natural. For students and parents — not admission guarantees.",
    whatsIncluded: pack(
      [
        "Learning-style portrait",
        "Motivation & focus themes",
        "Mentor / teacher motifs",
        "Higher-study symbolism",
        "Parent–student conversation page",
        "Study-ritual suggestions (reflective)",
      ],
      [
        "1. How charts talk about learning",
        "2. Your study signature",
        "3. Support systems",
        "4. Path experiments",
      ],
      ["Students", "Parents", "Adult learners returning to study"],
      ["Better study experiments", "Shared language at home"],
    ),
    faqs: COMMON_FAQS,
    deliveryNote: "Education PDF in dashboard after payment.",
    reportTemplateKey: "education-analysis",
    sortOrder: 3,
    pageEstimate: 12,
  },
  {
    name: "Family Dynamics Report",
    slug: "family-analysis",
    categorySlug: "wealth",
    shortDescription: "Household bonds, parental themes, and family-role storytelling from the chart.",
    description:
      "Explores family-role motifs, support patterns, and household harmony themes. Designed for empathy — not blame. Distinct from couple matching; this is about the wider family system.",
    whatsIncluded: pack(
      [
        "Parental & lineage motifs (symbolic)",
        "Your role in the family system",
        "Support & boundary themes",
        "Sibling / extended-family colour notes",
        "Repair & appreciation prompts",
        "Shareable family PDF",
      ],
      [
        "1. Reading family charts kindly",
        "2. Your household role",
        "3. Bonds & boundaries",
        "4. Healing conversations",
      ],
      ["Adults navigating family complexity", "New parents", "Anyone seeking kinder home dialogue"],
      ["Empathy scripts", "Role clarity without blame"],
    ),
    faqs: COMMON_FAQS,
    deliveryNote: "Family PDF delivered digitally.",
    reportTemplateKey: "family-analysis",
    sortOrder: 4,
    pageEstimate: 14,
  },

  // ── Dosha & Planets ─────────────────────────────────────
  {
    name: "Complete Dosha Scan",
    slug: "dosha-analysis",
    categorySlug: "dosha",
    shortDescription: "Combined dosha overview explained in calm, curiosity-friendly language.",
    description:
      "One scan covering commonly discussed dosha flags with severity context and what each traditionally means — plus what it does not mean. Points you to specialised Manglik, Rahu-Ketu, or Sade Sati reports only when relevant, avoiding duplicate purchases.",
    whatsIncluded: pack(
      [
        "Multi-dosha checklist with plain explanations",
        "What is present vs absent in your chart (informational)",
        "Priority ranking of what to study next",
        "Remedial tradition overview (optional, non-prescriptive)",
        "Fear-reduction FAQ inside the PDF",
        "Digital report",
      ],
      [
        "1. Dosha literacy without panic",
        "2. Your scan results",
        "3. Context & proportion",
        "4. Next specialised reports (only if needed)",
      ],
      ["Anyone hearing dosha concerns for the first time", "Families wanting a calm overview"],
      ["Less fear, more clarity", "A map of which deep-dive to buy"],
    ),
    faqs: COMMON_FAQS,
    deliveryNote: "Scan PDF after payment.",
    reportTemplateKey: "dosha-analysis",
    sortOrder: 1,
    pageEstimate: 15,
  },
  {
    name: "Manglik Analysis",
    slug: "manglik-analysis",
    categorySlug: "dosha",
    shortDescription: "Mars/Manglik flag check with calm explanation for marriage discussions.",
    description:
      "Dedicated Manglik report for marriage conversations. Explains classical conditions, cancellation themes where applicable, and how to talk about Mars energy without stigma. Complementary to Guna Milan — not a repeat of the full dosha scan.",
    whatsIncluded: pack(
      [
        "Manglik presence assessment (informational)",
        "Classical cancellation notes if relevant",
        "Mars temperament chapter",
        "Partner-discussion script",
        "Link-outs to matching reports",
      ],
      [
        "1. Manglik without myth-stacking",
        "2. Your Mars placement story",
        "3. Match-context page",
        "4. Conversation guide",
      ],
      ["People in active match discussions", "Anyone labelled Manglik and seeking clarity"],
      ["Calm facts for families", "Dignity around Mars themes"],
    ),
    faqs: COMMON_FAQS,
    deliveryNote: "Manglik PDF shortly after payment.",
    reportTemplateKey: "manglik-analysis",
    sortOrder: 2,
    pageEstimate: 10,
  },
  {
    name: "Rahu-Ketu & Axis Themes",
    slug: "rahu-ketu-analysis",
    categorySlug: "dosha",
    shortDescription: "North/south node themes: cravings, detours, karma axis, and growth edges.",
    description:
      "A focused axis report on Rahu and Ketu — life appetite, release patterns, and the houses they colour. Includes Kaal Sarp style axis discussion when the chart pattern applies, without selling fear.",
    whatsIncluded: pack(
      [
        "Rahu house & sign deep-dive",
        "Ketu house & sign deep-dive",
        "Axis life-lesson narrative",
        "Kaal Sarp pattern note if applicable",
        "Grounding practices for reflection (non-medical)",
        "PDF report",
      ],
      [
        "1. Nodes as storytellers",
        "2. Rahu chapter",
        "3. Ketu chapter",
        "4. Axis synthesis",
        "5. Optional pattern notes",
      ],
      ["People in big identity shifts", "Anyone curious about node mythology"],
      ["Language for craving vs release", "Gentler self-talk in intense chapters"],
    ),
    faqs: COMMON_FAQS,
    deliveryNote: "Node-axis PDF after payment.",
    reportTemplateKey: "rahu-ketu-analysis",
    sortOrder: 3,
    pageEstimate: 14,
  },
  {
    name: "Sade Sati Report",
    slug: "sade-sati-report",
    categorySlug: "dosha",
    shortDescription: "Saturn Sade Sati phase status with calm transit storytelling.",
    description:
      "Checks whether Sade Sati-style Saturn transit themes are active relative to your Moon, explains phases, and offers reflective coping frames. No doom language — aligned with how careful modern platforms educate on Shani periods.",
    whatsIncluded: pack(
      [
        "Phase status (before / during / after style framing)",
        "Moon & Saturn relationship notes",
        "Theme map: work, bonds, health-of-habits",
        "Supportive routine suggestions (reflective)",
        "Timeline graphic",
      ],
      [
        "1. Sade Sati literacy",
        "2. Your status",
        "3. Phase themes",
        "4. Steady practices",
      ],
      ["Anyone told they are “in Sade Sati”", "People feeling long Saturn chapters"],
      ["Orientation without fear", "Practical steadiness prompts"],
    ),
    faqs: COMMON_FAQS,
    deliveryNote: "Sade Sati PDF in dashboard after payment.",
    reportTemplateKey: "sade-sati-report",
    sortOrder: 4,
    pageEstimate: 12,
  },
  {
    name: "Saturn Life Lessons",
    slug: "saturn-analysis",
    categorySlug: "dosha",
    shortDescription: "Shani symbolism around discipline, patience, responsibility, and mastery.",
    description:
      "A planet spotlight on Saturn alone — distinct from Sade Sati transit timing. Covers natal Saturn house/sign, aspects, and the craft of patience. For readers who want mastery themes without a full graha-by-graha pack.",
    whatsIncluded: pack(
      [
        "Natal Saturn placement portrait",
        "Responsibility & boundary themes",
        "Mastery path suggestions",
        "Relationship to time & aging gracefully",
        "PDF spotlight",
      ],
      [
        "1. Meeting Shani kindly",
        "2. Your Saturn signature",
        "3. Lessons & strengths",
        "4. Practice page",
      ],
      ["People working on discipline kindly", "Anyone with strong Saturn contacts"],
      ["Respect for limits", "Long-game motivation"],
    ),
    faqs: COMMON_FAQS,
    deliveryNote: "Saturn PDF after payment.",
    reportTemplateKey: "saturn-analysis",
    sortOrder: 5,
    pageEstimate: 11,
  },

  // ── Face ────────────────────────────────────────────────
  {
    name: "AI Face Self-Discovery",
    slug: "ai-face-self-discovery",
    categorySlug: "self-discovery",
    shortDescription: "Playful AI face scan that turns features into personality story prompts.",
    description:
      "Upload-friendly face self-discovery experience translated into a personality story PDF. Entertainment and reflection only — not a medical, forensic, or scientific personality test. Structured with clear chapters like leading consumer astrology apps: traits, communication, growth.",
    whatsIncluded: pack(
      [
        "Feature-inspired personality narrative",
        "Communication style notes",
        "Strength & softness balance",
        "Relationship vibe prompts",
        "Shareable PDF summary",
        "Prominent entertainment disclaimer",
      ],
      [
        "1. How face storytelling works here",
        "2. Your trait mosaic",
        "3. Social style",
        "4. Growth edges",
        "5. Journal prompts",
      ],
      ["Curious self-explorers", "Gift buyers wanting a fun PDF", "People pairing face + numerology"],
      ["A light, insightful read", "Conversation starters"],
    ),
    faqs: [
      ...COMMON_FAQS,
      {
        q: "Is face reading scientific?",
        a: "No. This is an interpretive entertainment experience for self-reflection. It is not a validated psychological or medical assessment.",
      },
    ],
    deliveryNote: "Report PDF after the face experience completes and payment confirms.",
    reportTemplateKey: "ai-face-self-discovery",
    sortOrder: 1,
    pageEstimate: 10,
  },
  {
    name: "Complete Face Reading Report",
    slug: "premium-face-reading",
    categorySlug: "self-discovery",
    shortDescription: "Extended face-reading PDF with richer chapters on presence, work, and bonds.",
    description:
      "The long-form face report for people who want more than a quick scan: presence, work persona, affection style, and growth map in separate chapters. Does not duplicate the short AI Face Self-Discovery — upgrade path for depth.",
    whatsIncluded: pack(
      [
        "Extended physiognomy-style chapters",
        "Presence & first-impression notes",
        "Work persona vignette",
        "Affection & trust style",
        "Strengths & growth matrix",
        "Premium-length PDF",
      ],
      [
        "1. Reading face lore responsibly",
        "2. Presence",
        "3. Work & craft",
        "4. Bonds",
        "5. Growth matrix",
      ],
      ["Readers who finished the short face report", "Coaches using symbolic tools", "Gift edition seekers"],
      ["Deeper narrative", "Richer shareable PDF"],
    ),
    faqs: COMMON_FAQS,
    deliveryNote: "Extended PDF after payment.",
    reportTemplateKey: "premium-face-reading",
    sortOrder: 2,
    pageEstimate: 18,
  },
  {
    name: "Strengths & Growth Map",
    slug: "strengths-growth-analysis",
    categorySlug: "self-discovery",
    shortDescription: "Balanced strengths and growth edges for mindful personal reflection.",
    description:
      "Chart-informed (and optionally face-informed) strengths inventory with compassionate growth edges. One job: self-awareness — not performance scoring.",
    whatsIncluded: pack(
      [
        "Top strength themes",
        "Growth edges without shame language",
        "Energy management notes",
        "30-day practice menu",
        "PDF workbook style",
      ],
      [
        "1. Strengths inventory",
        "2. Growth edges",
        "3. Energy & boundaries",
        "4. 30-day menu",
      ],
      ["Journalers", "People in coaching", "Anyone wanting a non-predictive development PDF"],
      ["Actionable kindness", "Clear practice menu"],
    ),
    faqs: COMMON_FAQS,
    deliveryNote: "Workbook PDF after payment.",
    reportTemplateKey: "strengths-growth-analysis",
    sortOrder: 3,
    pageEstimate: 12,
  },

  // ── Numerology ──────────────────────────────────────────
  {
    name: "Complete Numerology Report",
    slug: "complete-numerology-report",
    categorySlug: "numerology",
    shortDescription: "All core numbers in one PDF — life path, destiny, soul urge, personality.",
    description:
      "Flagship numerology pack combining Life Path, Destiny, Soul Urge, and Personality numbers with synthesis chapters. Buy this instead of four separate number PDFs. Name and mobile deep-dives remain separate specialised products.",
    whatsIncluded: pack(
      [
        "Life Path number chapter",
        "Destiny / Expression number chapter",
        "Soul Urge chapter",
        "Personality number chapter",
        "Synthesis: how the four interact",
        "Year-ahead personal number teaser",
        "Complete PDF",
      ],
      [
        "1. Numerology literacy",
        "2–5. Core numbers",
        "6. Synthesis",
        "7. Next steps",
      ],
      ["Number lovers wanting one complete file", "Gift buyers", "People new to numerology"],
      ["Full core profile", "Clear upsell only when specialised"],
    ),
    faqs: COMMON_FAQS,
    deliveryNote: "Complete numerology PDF after payment.",
    reportTemplateKey: "complete-numerology-report",
    sortOrder: 1,
    pageEstimate: 20,
  },
  {
    name: "Name Numerology",
    slug: "name-numerology",
    categorySlug: "numerology",
    shortDescription: "Full-name number breakdown with interpretive notes for identity & brand feel.",
    description:
      "Dedicated name analysis — distinct from the Complete Numerology Report’s core birth numbers. Useful for personal name reflection or gentle brand/name experiments (not legal name-change advice).",
    whatsIncluded: pack(
      [
        "Letter-by-letter value map",
        "Expression themes from the full name",
        "Short-name / nickname comparison if provided",
        "Identity language suggestions",
        "PDF report",
      ],
      [
        "1. Name as vibration metaphor",
        "2. Your map",
        "3. Themes",
        "4. Reflection",
      ],
      ["People considering name styling", "Creators naming projects", "Parents exploring name feel"],
      ["Name literacy", "Creative brainstorming prompts"],
    ),
    faqs: COMMON_FAQS,
    deliveryNote: "Name PDF after payment.",
    reportTemplateKey: "name-numerology",
    sortOrder: 2,
    pageEstimate: 10,
  },
  {
    name: "Mobile Number Numerology",
    slug: "mobile-number-numerology",
    categorySlug: "numerology",
    shortDescription: "Phone-number numerology reading presented as entertainment.",
    description:
      "A fun, specialised reading of your mobile number pattern. Purely entertainment — keep your number if it serves your life; this is symbolic play.",
    whatsIncluded: pack(
      [
        "Digit compound & reduction",
        "Communication vibe notes",
        "Do-not-obsess reminder page",
        "PDF summary",
      ],
      [
        "1. Playful framing",
        "2. Number story",
        "3. Vibe notes",
      ],
      ["Curious subscribers", "People who enjoy number games"],
      ["A light read", "No pressure to change numbers"],
    ),
    faqs: COMMON_FAQS,
    deliveryNote: "Mobile numerology PDF after payment.",
    reportTemplateKey: "mobile-number-numerology",
    sortOrder: 3,
    pageEstimate: 6,
  },
  {
    name: "Personal Year Forecast",
    slug: "personal-year-report",
    categorySlug: "numerology",
    shortDescription: "Current personal year themes for reflective planning and curiosity.",
    description:
      "Numerology personal year cycle explained month-flavoured themes for the current year. Complementary to Vedic Year Ahead — different system, different lens.",
    whatsIncluded: pack(
      [
        "Personal year number & meaning",
        "Quarter-by-quarter theme map",
        "Focus vs rest suggestions",
        "Comparison note vs Vedic annual forecast",
        "PDF forecast",
      ],
      [
        "1. Personal year system",
        "2. Your year number",
        "3. Quarterly map",
        "4. Integration tips",
      ],
      ["Planners who like yearly themes", "People who already own Complete Numerology"],
      ["A year lens for journaling", "Gentle pacing ideas"],
    ),
    faqs: COMMON_FAQS,
    deliveryNote: "Personal year PDF after payment.",
    reportTemplateKey: "personal-year-report",
    sortOrder: 4,
    pageEstimate: 12,
  },

  // ── Horoscopes & Transits ───────────────────────────────
  {
    name: "Personalized Year Ahead",
    slug: "annual-life-forecast",
    categorySlug: "daily-astrology",
    shortDescription: "Birthday-to-birthday year-ahead forecast for reflective journaling.",
    description:
      "A Vedic-flavoured annual forecast keyed to your chart — month clusters, dasha climate, and life-area highlights. Longer and more personal than generic rashifal. Daily/weekly blurbs stay free/membership-oriented; this is the deep annual PDF.",
    whatsIncluded: pack(
      [
        "12-month theme map",
        "Career / bonds / growth highlight reels",
        "Quieter vs louder months (symbolic)",
        "Journal prompts per quarter",
        "Long-form PDF",
      ],
      [
        "1. How to use a year-ahead",
        "2. Annual climate",
        "3. Month clusters",
        "4. Area spotlights",
        "5. Closing practices",
      ],
      ["Birthday gift buyers", "Planners wanting chart-aware years", "Members upgrading from daily blurbs"],
      ["A year companion PDF", "Better pacing for goals"],
    ),
    faqs: COMMON_FAQS,
    deliveryNote: "Annual PDF after payment.",
    reportTemplateKey: "annual-life-forecast",
    sortOrder: 1,
    pageEstimate: 24,
  },
  {
    name: "Planetary Transit Report",
    slug: "planetary-transit-report",
    categorySlug: "daily-astrology",
    shortDescription: "Gochar highlights when major planets shift signs or houses for you.",
    description:
      "Transit (gochar) report focused on how current outer-planet movements colour your natal houses. Distinct from the Year Ahead narrative — this is the technical “what’s moving now” brief.",
    whatsIncluded: pack(
      [
        "Major transit list relevant to your chart",
        "House activation notes",
        "Opportunity vs pressure framing (symbolic)",
        "30–90 day watchlist",
        "PDF brief",
      ],
      [
        "1. Transits 101",
        "2. Active gochar for you",
        "3. House stories",
        "4. Watchlist",
      ],
      ["Astrology students", "People feeling a strong transit season"],
      ["Technical clarity", "Focused near-term lens"],
    ),
    faqs: COMMON_FAQS,
    deliveryNote: "Transit PDF after payment.",
    reportTemplateKey: "planetary-transit-report",
    sortOrder: 2,
    pageEstimate: 14,
  },
  {
    name: "Personalized Monthly Guidance",
    slug: "personalized-monthly-guidance",
    categorySlug: "daily-astrology",
    shortDescription: "Chart-aware month-ahead notes for mood, focus, and gentle planning.",
    description:
      "One month, personalised. Bridges free daily horoscope and the full Year Ahead — ideal if you want depth without an annual commitment.",
    whatsIncluded: pack(
      [
        "Month overview keyed to your chart",
        "Week-flavoured themes",
        "Focus / rest / connect prompts",
        "PDF for the selected month",
      ],
      [
        "1. Month climate",
        "2. Weekly colour",
        "3. Practices",
      ],
      ["Busy professionals", "Anyone testing personalised guidance before annual"],
      ["A practical month companion", "Low-commitment depth"],
    ),
    faqs: COMMON_FAQS,
    deliveryNote: "Monthly PDF after payment.",
    reportTemplateKey: "personalized-monthly-guidance",
    sortOrder: 3,
    pageEstimate: 8,
  },
];

export const MEMBERSHIP_PRODUCT = {
  name: "Complete Self Discovery Membership",
  slug: "complete-self-discovery-membership",
  categorySlug: "self-discovery",
  shortDescription:
    "Annual membership with access to self-discovery reports, daily alerts, and member pricing.",
  description:
    "Unlock the self-discovery catalog, daily horoscope alerts, and member benefits for one year. Membership does not invent verified testimonials or guaranteed outcomes — it simply unlocks tools for ongoing reflection.",
  membershipPriceYearly: 2999,
  reportTemplateKey: "membership-self-discovery",
  sortOrder: 0,
  whatsIncluded: [
    "Access to self-discovery report catalog per plan terms",
    "Daily horoscope & moon sign alerts",
    "Member pricing on select reports",
    "Priority PDF generation",
    "Family member profiles",
  ],
  faqs: COMMON_FAQS,
};

export const SYSTEM_SETTINGS = [
  { key: "brand.name", value: "JyotishKundali", group: "brand", label: "Brand name" },
  { key: "brand.tagline", value: "Know Yourself. Understand Your Path.", group: "brand", label: "Tagline" },
  { key: "brand.domain", value: "jyotishkundali.com", group: "brand", label: "Primary domain" },
  { key: "brand.support_email", value: "support@jyotishkundali.com", group: "brand", label: "Support email" },
  { key: "brand.support_phone", value: "+91-0000000000", group: "brand", label: "Support phone" },
  { key: "commerce.currency", value: "INR", group: "commerce", label: "Default currency" },
  { key: "commerce.default_report_price", value: 499, group: "commerce", label: "Default report price (INR)" },
  { key: "commerce.membership_yearly_price", value: 2999, group: "commerce", label: "Membership yearly price (INR)" },
  { key: "reports.delivery_note", value: "PDF delivered within minutes after payment.", group: "reports", label: "Default delivery note" },
  { key: "reports.default_language", value: "en", group: "reports", label: "Default report language" },
  { key: "reports.languages_available", value: ["en", "hi"], group: "reports", label: "Available report languages" },
  { key: "astrology.ayanamsa", value: "lahiri", group: "astrology", label: "Default ayanamsa" },
  { key: "astrology.house_system", value: "whole_sign", group: "astrology", label: "Default house system" },
] as const;

/** Slugs that remain active after reseed — everything else is deactivated. */
export const ACTIVE_PRODUCT_SLUGS = new Set([
  ...PRODUCT_SEEDS.map((p) => p.slug),
  MEMBERSHIP_PRODUCT.slug,
]);
