export interface CategorySeed {
  name: string;
  slug: string;
  description: string;
  sortOrder: number;
}

export interface ProductSeed {
  name: string;
  slug: string;
  categorySlug: string;
  shortDescription: string;
  reportTemplateKey: string;
  sortOrder: number;
}

export const CATEGORY_SEEDS: CategorySeed[] = [
  {
    name: "Kundali",
    slug: "kundali",
    description: "Birth chart reports, divisional charts, and dasha timelines.",
    sortOrder: 1,
  },
  {
    name: "Marriage",
    slug: "marriage",
    description: "Matching, compatibility, and marriage timing reports.",
    sortOrder: 2,
  },
  {
    name: "Career",
    slug: "career",
    description: "Profession, education, and business guidance reports.",
    sortOrder: 3,
  },
  {
    name: "Wealth",
    slug: "wealth",
    description: "Finance, property, and prosperity themed reports.",
    sortOrder: 4,
  },
  {
    name: "Dosha",
    slug: "dosha",
    description: "Dosha checks and remedy-oriented reports.",
    sortOrder: 5,
  },
  {
    name: "Self Discovery",
    slug: "self-discovery",
    description: "Personality, purpose, and life-path insights.",
    sortOrder: 6,
  },
  {
    name: "Numerology",
    slug: "numerology",
    description: "Name and number based reports and tools.",
    sortOrder: 7,
  },
  {
    name: "Daily Astrology",
    slug: "daily-astrology",
    description: "Horoscopes, panchang, muhurat, and transit alerts.",
    sortOrder: 8,
  },
];

export const PRODUCT_SEEDS: ProductSeed[] = [
  // Kundali (10)
  {
    name: "Complete Janma Kundali (~20 Page PDF)",
    slug: "complete-janma-kundali",
    categorySlug: "kundali",
    shortDescription: "Full birth-time Vedic report with houses, dasha, yogas, and PDF delivery.",
    reportTemplateKey: "janma-kundali-full",
    sortOrder: 1,
  },
  {
    name: "Basic Birth Chart Report",
    slug: "basic-birth-chart",
    categorySlug: "kundali",
    shortDescription: "Essential lagna chart with planetary positions and house overview.",
    reportTemplateKey: "birth-chart-basic",
    sortOrder: 2,
  },
  {
    name: "Lagna Analysis Report",
    slug: "lagna-analysis",
    categorySlug: "kundali",
    shortDescription: "Focused reading of your ascendant sign and its influence.",
    reportTemplateKey: "lagna-analysis",
    sortOrder: 3,
  },
  {
    name: "Planet Positions Report",
    slug: "planet-positions",
    categorySlug: "kundali",
    shortDescription: "Detailed table of sign, degree, nakshatra, pada, and house for all grahas.",
    reportTemplateKey: "planet-positions",
    sortOrder: 4,
  },
  {
    name: "House-wise Reading (1–12 Bhav)",
    slug: "house-wise-reading",
    categorySlug: "kundali",
    shortDescription: "Interpretation of each of the twelve houses in your chart.",
    reportTemplateKey: "house-readings",
    sortOrder: 5,
  },
  {
    name: "Navamsa (D9) Chart Report",
    slug: "navamsa-d9-report",
    categorySlug: "kundali",
    shortDescription: "Navamsa divisional chart for dharma and relationship themes.",
    reportTemplateKey: "navamsa-d9",
    sortOrder: 6,
  },
  {
    name: "Dasamsha (D10) Chart Report",
    slug: "dasamsha-d10-report",
    categorySlug: "kundali",
    shortDescription: "Dasamsha chart focused on career and professional direction.",
    reportTemplateKey: "dasamsha-d10",
    sortOrder: 7,
  },
  {
    name: "Divisional Charts Bundle (D9+D10+D7)",
    slug: "divisional-charts-bundle",
    categorySlug: "kundali",
    shortDescription: "Combined report covering key divisional charts in one PDF.",
    reportTemplateKey: "divisional-bundle",
    sortOrder: 8,
  },
  {
    name: "Vimshottari Dasha Timeline",
    slug: "vimshottari-dasha-timeline",
    categorySlug: "kundali",
    shortDescription: "Mahadasha and Antardasha periods with start and end dates.",
    reportTemplateKey: "vimshottari-dasha",
    sortOrder: 9,
  },
  {
    name: "Baby Kundali Report",
    slug: "baby-kundali-report",
    categorySlug: "kundali",
    shortDescription: "Birth chart report prepared for a newborn or young child.",
    reportTemplateKey: "baby-kundali",
    sortOrder: 10,
  },

  // Marriage (10)
  {
    name: "Kundali Milan (Gun Milan)",
    slug: "kundali-milan-gun-milan",
    categorySlug: "marriage",
    shortDescription: "Traditional gun milan score for marriage compatibility.",
    reportTemplateKey: "gun-milan",
    sortOrder: 1,
  },
  {
    name: "Ashtakoot 36-Point Matching",
    slug: "ashtakoot-36-point",
    categorySlug: "marriage",
    shortDescription: "Detailed ashtakoot breakdown across eight koot categories.",
    reportTemplateKey: "ashtakoot-36",
    sortOrder: 2,
  },
  {
    name: "Manglik Comparison for Couples",
    slug: "manglik-comparison-couples",
    categorySlug: "marriage",
    shortDescription: "Side-by-side manglik assessment for two birth charts.",
    reportTemplateKey: "manglik-compare",
    sortOrder: 3,
  },
  {
    name: "D9 Marriage Compatibility",
    slug: "d9-marriage-compatibility",
    categorySlug: "marriage",
    shortDescription: "Navamsa-based compatibility notes for long-term partnership.",
    reportTemplateKey: "d9-marriage",
    sortOrder: 4,
  },
  {
    name: "Love Compatibility Report",
    slug: "love-compatibility-report",
    categorySlug: "marriage",
    shortDescription: "Relationship compatibility reading for romantic partners.",
    reportTemplateKey: "love-compatibility",
    sortOrder: 5,
  },
  {
    name: "Marriage Timing Report",
    slug: "marriage-timing-report",
    categorySlug: "marriage",
    shortDescription: "Dasha and transit based windows relevant to marriage timing.",
    reportTemplateKey: "marriage-timing",
    sortOrder: 6,
  },
  {
    name: "Spouse Characteristics Report",
    slug: "spouse-characteristics",
    categorySlug: "marriage",
    shortDescription: "Themes about partner qualities from the 7th house and D9.",
    reportTemplateKey: "spouse-characteristics",
    sortOrder: 7,
  },
  {
    name: "Pre-Wedding Couple Report",
    slug: "pre-wedding-couple-report",
    categorySlug: "marriage",
    shortDescription: "Combined couple report for families before wedding planning.",
    reportTemplateKey: "pre-wedding-couple",
    sortOrder: 8,
  },
  {
    name: "Shaadi Pack",
    slug: "shaadi-pack",
    categorySlug: "marriage",
    shortDescription: "Bundle with gun milan, manglik compare, and shareable PDF.",
    reportTemplateKey: "shaadi-pack",
    sortOrder: 9,
  },
  {
    name: "Post-Marriage Harmony Report",
    slug: "post-marriage-harmony",
    categorySlug: "marriage",
    shortDescription: "Guidance themes for understanding and improving marital harmony.",
    reportTemplateKey: "post-marriage-harmony",
    sortOrder: 10,
  },

  // Career (10)
  {
    name: "Career & Profession Report",
    slug: "career-profession-report",
    categorySlug: "career",
    shortDescription: "10th-house focused guidance for job and profession decisions.",
    reportTemplateKey: "career-profession",
    sortOrder: 1,
  },
  {
    name: "Job Change Timing Report",
    slug: "job-change-timing",
    categorySlug: "career",
    shortDescription: "Dasha periods that may support or caution job transitions.",
    reportTemplateKey: "job-change-timing",
    sortOrder: 2,
  },
  {
    name: "Government Job Analysis",
    slug: "government-job-analysis",
    categorySlug: "career",
    shortDescription: "Chart factors often reviewed for public sector career paths.",
    reportTemplateKey: "government-job",
    sortOrder: 3,
  },
  {
    name: "Business Suitability Report",
    slug: "business-suitability",
    categorySlug: "career",
    shortDescription: "Indicators for entrepreneurship versus salaried work.",
    reportTemplateKey: "business-suitability",
    sortOrder: 4,
  },
  {
    name: "Education & Study Report",
    slug: "education-study-report",
    categorySlug: "career",
    shortDescription: "5th-house themes for learning style and academic direction.",
    reportTemplateKey: "education-study",
    sortOrder: 5,
  },
  {
    name: "Student Pack",
    slug: "student-pack",
    categorySlug: "career",
    shortDescription: "Education and career timing notes designed for students.",
    reportTemplateKey: "student-pack",
    sortOrder: 6,
  },
  {
    name: "Competitive Exam Timing",
    slug: "competitive-exam-timing",
    categorySlug: "career",
    shortDescription: "Periods that may be more supportive for exam preparation and attempts.",
    reportTemplateKey: "exam-timing",
    sortOrder: 7,
  },
  {
    name: "Promotion & Growth Report",
    slug: "promotion-growth-report",
    categorySlug: "career",
    shortDescription: "Career growth themes from dasha and 10th-house indicators.",
    reportTemplateKey: "promotion-growth",
    sortOrder: 8,
  },
  {
    name: "Business Pack",
    slug: "business-pack",
    categorySlug: "career",
    shortDescription: "Career notes plus business muhurat shortlist in one report.",
    reportTemplateKey: "business-pack",
    sortOrder: 9,
  },
  {
    name: "Foreign Career Opportunities",
    slug: "foreign-career-opportunities",
    categorySlug: "career",
    shortDescription: "Themes related to working or settling abroad from your chart.",
    reportTemplateKey: "foreign-career",
    sortOrder: 10,
  },

  // Wealth (10)
  {
    name: "Wealth & Finance Report",
    slug: "wealth-finance-report",
    categorySlug: "wealth",
    shortDescription: "2nd and 11th-house themes for income and financial habits.",
    reportTemplateKey: "wealth-finance",
    sortOrder: 1,
  },
  {
    name: "Property & Real Estate Timing",
    slug: "property-real-estate-timing",
    categorySlug: "wealth",
    shortDescription: "Periods that may be more favourable for property decisions.",
    reportTemplateKey: "property-timing",
    sortOrder: 2,
  },
  {
    name: "Business Profit Analysis",
    slug: "business-profit-analysis",
    categorySlug: "wealth",
    shortDescription: "Chart factors reviewed for business revenue and cash flow themes.",
    reportTemplateKey: "business-profit",
    sortOrder: 3,
  },
  {
    name: "Investment Timing Report",
    slug: "investment-timing",
    categorySlug: "wealth",
    shortDescription: "General timing notes for financial commitments—not investment advice.",
    reportTemplateKey: "investment-timing",
    sortOrder: 4,
  },
  {
    name: "Debt & Financial Stress Report",
    slug: "debt-financial-stress",
    categorySlug: "wealth",
    shortDescription: "Themes around financial pressure and repayment cycles in the chart.",
    reportTemplateKey: "debt-stress",
    sortOrder: 5,
  },
  {
    name: "Dhana Yoga Analysis",
    slug: "dhana-yoga-analysis",
    categorySlug: "wealth",
    shortDescription: "Detection and explanation of selected wealth-related yogas.",
    reportTemplateKey: "dhana-yoga",
    sortOrder: 6,
  },
  {
    name: "Inheritance & Legacy Report",
    slug: "inheritance-legacy",
    categorySlug: "wealth",
    shortDescription: "8th-house themes related to inheritance and shared assets.",
    reportTemplateKey: "inheritance-legacy",
    sortOrder: 7,
  },
  {
    name: "Sudden Gains Analysis",
    slug: "sudden-gains-analysis",
    categorySlug: "wealth",
    shortDescription: "Yoga and dasha patterns sometimes associated with unexpected gains.",
    reportTemplateKey: "sudden-gains",
    sortOrder: 8,
  },
  {
    name: "Lakshmi Yoga Report",
    slug: "lakshmi-yoga-report",
    categorySlug: "wealth",
    shortDescription: "Focused report on Lakshmi yoga presence and related themes.",
    reportTemplateKey: "lakshmi-yoga",
    sortOrder: 9,
  },
  {
    name: "Financial Dasha Forecast",
    slug: "financial-dasha-forecast",
    categorySlug: "wealth",
    shortDescription: "Mahadasha overview with finance-relevant themes highlighted.",
    reportTemplateKey: "financial-dasha",
    sortOrder: 10,
  },

  // Dosha (10)
  {
    name: "Manglik Dosha Check",
    slug: "manglik-dosha-check",
    categorySlug: "dosha",
    shortDescription: "Standalone manglik assessment with severity notes.",
    reportTemplateKey: "manglik-dosha",
    sortOrder: 1,
  },
  {
    name: "Kaal Sarp Dosha Analysis",
    slug: "kaal-sarp-dosha",
    categorySlug: "dosha",
    shortDescription: "Kaal sarp pattern check with plain-language explanation.",
    reportTemplateKey: "kaal-sarp",
    sortOrder: 2,
  },
  {
    name: "Pitra Dosha Report",
    slug: "pitra-dosha-report",
    categorySlug: "dosha",
    shortDescription: "Traditional pitra dosha indicators explained without fear language.",
    reportTemplateKey: "pitra-dosha",
    sortOrder: 3,
  },
  {
    name: "Shani Dosha Analysis",
    slug: "shani-dosha-analysis",
    categorySlug: "dosha",
    shortDescription: "Saturn-related dosha flags and their chart context.",
    reportTemplateKey: "shani-dosha",
    sortOrder: 4,
  },
  {
    name: "Sade Sati Report",
    slug: "sade-sati-report",
    categorySlug: "dosha",
    shortDescription: "Sade sati phase status and general transit notes.",
    reportTemplateKey: "sade-sati",
    sortOrder: 5,
  },
  {
    name: "Grahan Dosha Check",
    slug: "grahan-dosha-check",
    categorySlug: "dosha",
    shortDescription: "Eclipse-related dosha indicators in the birth chart.",
    reportTemplateKey: "grahan-dosha",
    sortOrder: 6,
  },
  {
    name: "Nadi Dosha Analysis",
    slug: "nadi-dosha-analysis",
    categorySlug: "dosha",
    shortDescription: "Nadi dosha check for marriage matching context.",
    reportTemplateKey: "nadi-dosha",
    sortOrder: 7,
  },
  {
    name: "Complete Dosha Scan",
    slug: "complete-dosha-scan",
    categorySlug: "dosha",
    shortDescription: "Combined scan of major dosha flags in one report.",
    reportTemplateKey: "dosha-scan",
    sortOrder: 8,
  },
  {
    name: "Dosha Remedies Report",
    slug: "dosha-remedies-report",
    categorySlug: "dosha",
    shortDescription: "Remedy suggestions mapped to detected dosha flags.",
    reportTemplateKey: "dosha-remedies",
    sortOrder: 9,
  },
  {
    name: "Gand Mool Nakshatra Check",
    slug: "gand-mool-nakshatra",
    categorySlug: "dosha",
    shortDescription: "Gand mool nakshatra birth flag with traditional notes.",
    reportTemplateKey: "gand-mool",
    sortOrder: 10,
  },

  // Self Discovery (10)
  {
    name: "Personality Blueprint Report",
    slug: "personality-blueprint",
    categorySlug: "self-discovery",
    shortDescription: "Lagna and key planet themes describing personality patterns.",
    reportTemplateKey: "personality-blueprint",
    sortOrder: 1,
  },
  {
    name: "Life Purpose Report",
    slug: "life-purpose-report",
    categorySlug: "self-discovery",
    shortDescription: "Dharma-oriented themes from lagna, Sun, and 9th-house indicators.",
    reportTemplateKey: "life-purpose",
    sortOrder: 2,
  },
  {
    name: "Strengths & Weaknesses Analysis",
    slug: "strengths-weaknesses",
    categorySlug: "self-discovery",
    shortDescription: "Balanced overview of supportive and challenging chart factors.",
    reportTemplateKey: "strengths-weaknesses",
    sortOrder: 3,
  },
  {
    name: "Spiritual Growth Report",
    slug: "spiritual-growth-report",
    categorySlug: "self-discovery",
    shortDescription: "9th and 12th-house themes for spiritual practice and reflection.",
    reportTemplateKey: "spiritual-growth",
    sortOrder: 4,
  },
  {
    name: "Health Tendencies Report",
    slug: "health-tendencies-report",
    categorySlug: "self-discovery",
    shortDescription: "Lifestyle tendency notes from the chart—not medical advice.",
    reportTemplateKey: "health-tendencies",
    sortOrder: 5,
  },
  {
    name: "Foreign Settlement Report",
    slug: "foreign-settlement-report",
    categorySlug: "self-discovery",
    shortDescription: "Themes related to travel, relocation, and life abroad.",
    reportTemplateKey: "foreign-settlement",
    sortOrder: 6,
  },
  {
    name: "Deep Report Bundle",
    slug: "deep-report-bundle",
    categorySlug: "self-discovery",
    shortDescription: "Full kundali PDF with extended career and year-ahead chapters.",
    reportTemplateKey: "deep-bundle",
    sortOrder: 7,
  },
  {
    name: "Life Path Snapshot",
    slug: "life-path-snapshot",
    categorySlug: "self-discovery",
    shortDescription: "Concise overview of core chart themes for quick self-understanding.",
    reportTemplateKey: "life-path-snapshot",
    sortOrder: 8,
  },
  {
    name: "Annual Self-Review Report",
    slug: "annual-self-review",
    categorySlug: "self-discovery",
    shortDescription: "Year-ahead personal themes for reflection and planning.",
    reportTemplateKey: "annual-self-review",
    sortOrder: 9,
  },
  {
    name: "Mind & Emotions Chapter",
    slug: "mind-emotions-chapter",
    categorySlug: "self-discovery",
    shortDescription: "Moon-led chapter on emotional patterns and mental rhythm.",
    reportTemplateKey: "mind-emotions",
    sortOrder: 10,
  },

  // Numerology (9)
  {
    name: "Name Numerology Report",
    slug: "name-numerology-report",
    categorySlug: "numerology",
    shortDescription: "Numerological breakdown of your full name.",
    reportTemplateKey: "name-numerology",
    sortOrder: 1,
  },
  {
    name: "Life Path Number Analysis",
    slug: "life-path-number",
    categorySlug: "numerology",
    shortDescription: "Life path number calculated from date of birth.",
    reportTemplateKey: "life-path-number",
    sortOrder: 2,
  },
  {
    name: "Destiny Number Report",
    slug: "destiny-number-report",
    categorySlug: "numerology",
    shortDescription: "Destiny number themes based on your name.",
    reportTemplateKey: "destiny-number",
    sortOrder: 3,
  },
  {
    name: "Lucky Name Suggestions",
    slug: "lucky-name-suggestions",
    categorySlug: "numerology",
    shortDescription: "Name spelling options aligned with favourable numerology totals.",
    reportTemplateKey: "lucky-name",
    sortOrder: 4,
  },
  {
    name: "Business Name Numerology",
    slug: "business-name-numerology",
    categorySlug: "numerology",
    shortDescription: "Numerology analysis for a business or brand name.",
    reportTemplateKey: "business-name-numerology",
    sortOrder: 5,
  },
  {
    name: "Mobile Number Analysis",
    slug: "mobile-number-analysis",
    categorySlug: "numerology",
    shortDescription: "Numerological reading of a mobile phone number.",
    reportTemplateKey: "mobile-number",
    sortOrder: 6,
  },
  {
    name: "Vehicle Number Analysis",
    slug: "vehicle-number-analysis",
    categorySlug: "numerology",
    shortDescription: "Numerology notes for a vehicle registration number.",
    reportTemplateKey: "vehicle-number",
    sortOrder: 7,
  },
  {
    name: "Compatibility by Numbers",
    slug: "compatibility-by-numbers",
    categorySlug: "numerology",
    shortDescription: "Numerology-based compatibility between two names or dates.",
    reportTemplateKey: "numerology-compatibility",
    sortOrder: 8,
  },
  {
    name: "Personal Year Numerology Forecast",
    slug: "personal-year-numerology",
    categorySlug: "numerology",
    shortDescription: "Personal year number and themes for the current cycle.",
    reportTemplateKey: "personal-year-numerology",
    sortOrder: 9,
  },

  // Daily Astrology (9)
  {
    name: "Daily Horoscope",
    slug: "daily-horoscope",
    categorySlug: "daily-astrology",
    shortDescription: "Personalized or sign-based daily horoscope content.",
    reportTemplateKey: "daily-horoscope",
    sortOrder: 1,
  },
  {
    name: "Weekly Rashifal",
    slug: "weekly-rashifal",
    categorySlug: "daily-astrology",
    shortDescription: "Seven-day rashifal overview for your moon sign.",
    reportTemplateKey: "weekly-rashifal",
    sortOrder: 2,
  },
  {
    name: "Monthly Forecast",
    slug: "monthly-forecast",
    categorySlug: "daily-astrology",
    shortDescription: "Month-ahead themes based on transits and your chart.",
    reportTemplateKey: "monthly-forecast",
    sortOrder: 3,
  },
  {
    name: "Yearly Rashifal (Rashi)",
    slug: "yearly-rashifal",
    categorySlug: "daily-astrology",
    shortDescription: "Annual rashifal themes for your moon sign.",
    reportTemplateKey: "yearly-rashifal",
    sortOrder: 4,
  },
  {
    name: "Panchang Today",
    slug: "panchang-today",
    categorySlug: "daily-astrology",
    shortDescription: "Today's panchang elements for your location.",
    reportTemplateKey: "panchang-today",
    sortOrder: 5,
  },
  {
    name: "Moon Sign Daily Alert",
    slug: "moon-sign-daily-alert",
    categorySlug: "daily-astrology",
    shortDescription: "Daily alert content keyed to your moon sign.",
    reportTemplateKey: "moon-sign-alert",
    sortOrder: 6,
  },
  {
    name: "Transit Alerts (Gochar)",
    slug: "transit-alerts-gochar",
    categorySlug: "daily-astrology",
    shortDescription: "Notifications when major planets change signs or houses.",
    reportTemplateKey: "transit-alerts",
    sortOrder: 7,
  },
  {
    name: "Muhurat Finder",
    slug: "muhurat-finder",
    categorySlug: "daily-astrology",
    shortDescription: "Auspicious date shortlist for weddings, griha pravesh, or business.",
    reportTemplateKey: "muhurat-finder",
    sortOrder: 8,
  },
  {
    name: "Yearly Varshphal",
    slug: "yearly-varshphal",
    categorySlug: "daily-astrology",
    shortDescription: "Birthday-to-birthday year-ahead varshphal overview.",
    reportTemplateKey: "varshphal",
    sortOrder: 9,
  },
];

export const MEMBERSHIP_PRODUCT = {
  name: "Complete Self Discovery Membership",
  slug: "complete-self-discovery-membership",
  categorySlug: "self-discovery",
  shortDescription:
    "Annual membership with access to self-discovery reports, daily alerts, and member pricing.",
  description:
    "Unlock the full self-discovery catalog, daily horoscope alerts, and member benefits for one year.",
  membershipPriceYearly: 2999,
  reportTemplateKey: "membership-self-discovery",
  sortOrder: 0,
};

export const SYSTEM_SETTINGS = [
  { key: "brand.name", value: "JyotishKundali", group: "brand", label: "Brand name" },
  { key: "brand.tagline", value: "Know Yourself. Understand Your Path.", group: "brand", label: "Tagline" },
  { key: "brand.domain", value: "jyotishkundali.com", group: "brand", label: "Primary domain" },
  { key: "brand.support_email", value: "support@jyotishkundali.com", group: "brand", label: "Support email" },
  { key: "brand.support_phone", value: "+91-0000000000", group: "brand", label: "Support phone" },
  { key: "commerce.currency", value: "INR", group: "commerce", label: "Default currency" },
  { key: "commerce.default_report_price", value: 499, group: "commerce", label: "Default report price (INR)" },
  { key: "commerce.membership_yearly_price", value: 2999, group: "commerce", label: "Membership yearly price (INR)" },
  { key: "reports.delivery_note", value: "PDF delivered within minutes after payment.", group: "reports", label: "Default delivery note" },
  { key: "reports.default_language", value: "en", group: "reports", label: "Default report language" },
  { key: "reports.languages_available", value: ["en", "hi"], group: "reports", label: "Available report languages" },
  { key: "astrology.ayanamsa", value: "lahiri", group: "astrology", label: "Default ayanamsa" },
  { key: "astrology.house_system", value: "whole_sign", group: "astrology", label: "Default house system" },
] as const;
