export interface CategorySeed {
  name: string;
  slug: string;
  description: string;
  sortOrder: number;
}

export interface ProductSeed {
  name: string;
  slug: string;
  categorySlug: string;
  shortDescription: string;
  reportTemplateKey: string;
  sortOrder: number;
}

export const CATEGORY_SEEDS: CategorySeed[] = [
  {
    name: "Kundali",
    slug: "kundali",
    description: "Birth chart reports, divisional charts, and dasha timelines.",
    sortOrder: 1,
  },
  {
    name: "Marriage & Relationships",
    slug: "marriage",
    description: "Matching, compatibility, and marriage timing reports.",
    sortOrder: 2,
  },
  {
    name: "Career & Business",
    slug: "career",
    description: "Profession, education, and business guidance reports.",
    sortOrder: 3,
  },
  {
    name: "Wealth & Life",
    slug: "wealth",
    description: "Finance, property, and life-path themed reports.",
    sortOrder: 4,
  },
  {
    name: "Dosha & Planets",
    slug: "dosha",
    description: "Dosha checks and planet-focused interpretive reports.",
    sortOrder: 5,
  },
  {
    name: "Self Discovery",
    slug: "self-discovery",
    description: "Face reading and personality insights for self-reflection.",
    sortOrder: 6,
  },
  {
    name: "Numerology",
    slug: "numerology",
    description: "Name and number based reports and tools.",
    sortOrder: 7,
  },
  {
    name: "Daily Astrology",
    slug: "daily-astrology",
    description: "Horoscopes, transits, and personalized daily guidance.",
    sortOrder: 8,
  },
];

export const PRODUCT_SEEDS: ProductSeed[] = [
  // Kundali (10)
  {
    name: "Janam Kundali",
    slug: "janam-kundali",
    categorySlug: "kundali",
    shortDescription: "Classic birth chart snapshot for curious self-exploration and reflection.",
    reportTemplateKey: "janam-kundali",
    sortOrder: 1,
  },
  {
    name: "Detailed Kundali",
    slug: "detailed-kundali",
    categorySlug: "kundali",
    shortDescription: "Expanded chart reading with richer house and planet storytelling.",
    reportTemplateKey: "detailed-kundali",
    sortOrder: 2,
  },
  {
    name: "Vedic Birth Chart",
    slug: "vedic-birth-chart",
    categorySlug: "kundali",
    shortDescription: "Traditional Vedic chart layout with interpretive notes for each graha.",
    reportTemplateKey: "vedic-birth-chart",
    sortOrder: 3,
  },
  {
    name: "Lagna Analysis",
    slug: "lagna-analysis",
    categorySlug: "kundali",
    shortDescription: "Ascendant-focused themes about temperament and first impressions.",
    reportTemplateKey: "lagna-analysis",
    sortOrder: 4,
  },
  {
    name: "Rashi Analysis",
    slug: "rashi-analysis",
    categorySlug: "kundali",
    shortDescription: "Moon sign storytelling about moods, instincts, and daily rhythm.",
    reportTemplateKey: "rashi-analysis",
    sortOrder: 5,
  },
  {
    name: "Nakshatra Analysis",
    slug: "nakshatra-analysis",
    categorySlug: "kundali",
    shortDescription: "Birth star themes for personality flair and symbolic life motifs.",
    reportTemplateKey: "nakshatra-analysis",
    sortOrder: 6,
  },
  {
    name: "Navamsa Chart",
    slug: "navamsa-chart",
    categorySlug: "kundali",
    shortDescription: "D9 divisional chart notes on dharma, partnership, and inner purpose.",
    reportTemplateKey: "navamsa-chart",
    sortOrder: 7,
  },
  {
    name: "Planetary Position Report",
    slug: "planetary-position-report",
    categorySlug: "kundali",
    shortDescription: "Sign, degree, nakshatra, and house table with light interpretation.",
    reportTemplateKey: "planetary-position-report",
    sortOrder: 8,
  },
  {
    name: "House Analysis",
    slug: "house-analysis",
    categorySlug: "kundali",
    shortDescription: "Twelve-house walkthrough of life themes from an entertainment lens.",
    reportTemplateKey: "house-analysis",
    sortOrder: 9,
  },
  {
    name: "Mahadasha & Antardasha",
    slug: "mahadasha-antardasha",
    categorySlug: "kundali",
    shortDescription: "Vimshottari timeline highlighting symbolic chapter changes over time.",
    reportTemplateKey: "mahadasha-antardasha",
    sortOrder: 10,
  },

  // Marriage & Relationships (10)
  {
    name: "Marriage Kundali",
    slug: "marriage-kundali",
    categorySlug: "marriage",
    shortDescription: "Partnership-oriented chart notes for romance and commitment curiosity.",
    reportTemplateKey: "marriage-kundali",
    sortOrder: 1,
  },
  {
    name: "Guna Milan",
    slug: "guna-milan",
    categorySlug: "marriage",
    shortDescription: "Traditional gun milan score presented as a fun compatibility snapshot.",
    reportTemplateKey: "guna-milan",
    sortOrder: 2,
  },
  {
    name: "Marriage Compatibility",
    slug: "marriage-compatibility",
    categorySlug: "marriage",
    shortDescription: "Side-by-side chart themes for long-term partnership storytelling.",
    reportTemplateKey: "marriage-compatibility",
    sortOrder: 3,
  },
  {
    name: "Love Compatibility",
    slug: "love-compatibility",
    categorySlug: "marriage",
    shortDescription: "Romantic chemistry reading for couples who enjoy symbolic matchmaking.",
    reportTemplateKey: "love-compatibility",
    sortOrder: 4,
  },
  {
    name: "Marriage Timing",
    slug: "marriage-timing",
    categorySlug: "marriage",
    shortDescription: "Dasha and transit windows framed as possible wedding chapter markers.",
    reportTemplateKey: "marriage-timing",
    sortOrder: 5,
  },
  {
    name: "Relationship Analysis",
    slug: "relationship-analysis",
    categorySlug: "marriage",
    shortDescription: "Balanced notes on communication style, attraction, and shared growth.",
    reportTemplateKey: "relationship-analysis",
    sortOrder: 6,
  },
  {
    name: "Manglik Analysis",
    slug: "manglik-analysis",
    categorySlug: "marriage",
    shortDescription: "Manglik flag check with calm, curiosity-friendly explanation.",
    reportTemplateKey: "manglik-analysis",
    sortOrder: 7,
  },
  {
    name: "Couple Kundali",
    slug: "couple-kundali",
    categorySlug: "marriage",
    shortDescription: "Combined couple report families can share before wedding planning chats.",
    reportTemplateKey: "couple-kundali",
    sortOrder: 8,
  },
  {
    name: "Partner Compatibility",
    slug: "partner-compatibility",
    categorySlug: "marriage",
    shortDescription: "Partner pairing themes from synastry-style chart comparison.",
    reportTemplateKey: "partner-compatibility",
    sortOrder: 9,
  },
  {
    name: "Marriage Prediction Report",
    slug: "marriage-prediction-report",
    categorySlug: "marriage",
    shortDescription: "Symbolic marriage storyline—not a guarantee, just reflective fun.",
    reportTemplateKey: "marriage-prediction-report",
    sortOrder: 10,
  },

  // Career & Business (10)
  {
    name: "Career Analysis",
    slug: "career-analysis",
    categorySlug: "career",
    shortDescription: "10th-house themes about work style, ambition, and professional identity.",
    reportTemplateKey: "career-analysis",
    sortOrder: 1,
  },
  {
    name: "Career Timing",
    slug: "career-timing",
    categorySlug: "career",
    shortDescription: "Dasha chapters that may feel more supportive for career moves.",
    reportTemplateKey: "career-timing",
    sortOrder: 2,
  },
  {
    name: "Business Kundali",
    slug: "business-kundali",
    categorySlug: "career",
    shortDescription: "Entrepreneurial chart motifs for founders who enjoy symbolic planning.",
    reportTemplateKey: "business-kundali",
    sortOrder: 3,
  },
  {
    name: "Business Success Analysis",
    slug: "business-success-analysis",
    categorySlug: "career",
    shortDescription: "Business growth storytelling from chart yogas and house emphasis.",
    reportTemplateKey: "business-success-analysis",
    sortOrder: 4,
  },
  {
    name: "Job/Career Direction",
    slug: "job-career-direction",
    categorySlug: "career",
    shortDescription: "Career path prompts based on chart strengths—not hiring advice.",
    reportTemplateKey: "job-career-direction",
    sortOrder: 5,
  },
  {
    name: "Leadership Style Analysis",
    slug: "leadership-style-analysis",
    categorySlug: "career",
    shortDescription: "How your chart may colour decision-making and team presence.",
    reportTemplateKey: "leadership-style-analysis",
    sortOrder: 6,
  },
  {
    name: "Entrepreneurship Analysis",
    slug: "entrepreneurship-analysis",
    categorySlug: "career",
    shortDescription: "Startup-friendly chart themes for self-starters and side-hustle dreamers.",
    reportTemplateKey: "entrepreneurship-analysis",
    sortOrder: 7,
  },
  {
    name: "Foreign Career Analysis",
    slug: "foreign-career-analysis",
    categorySlug: "career",
    shortDescription: "Abroad-work motifs from chart indicators—exploratory, not immigration advice.",
    reportTemplateKey: "foreign-career-analysis",
    sortOrder: 8,
  },
  {
    name: "Government Job Astrology",
    slug: "government-job-astrology",
    categorySlug: "career",
    shortDescription: "Public-sector career symbolism reviewed for entertainment and reflection.",
    reportTemplateKey: "government-job-astrology",
    sortOrder: 9,
  },
  {
    name: "Professional Growth Report",
    slug: "professional-growth-report",
    categorySlug: "career",
    shortDescription: "Promotion and skill-growth themes from dasha and 10th-house cues.",
    reportTemplateKey: "professional-growth-report",
    sortOrder: 10,
  },

  // Wealth & Life (10)
  {
    name: "Wealth Analysis",
    slug: "wealth-analysis",
    categorySlug: "wealth",
    shortDescription: "2nd and 11th-house money motifs for reflective financial curiosity.",
    reportTemplateKey: "wealth-analysis",
    sortOrder: 1,
  },
  {
    name: "Financial Astrology",
    slug: "financial-astrology",
    categorySlug: "wealth",
    shortDescription: "Symbolic finance themes—not investment, tax, or legal guidance.",
    reportTemplateKey: "financial-astrology",
    sortOrder: 2,
  },
  {
    name: "Property Analysis",
    slug: "property-analysis",
    categorySlug: "wealth",
    shortDescription: "Home and land symbolism from chart houses and transits.",
    reportTemplateKey: "property-analysis",
    sortOrder: 3,
  },
  {
    name: "Foreign Settlement",
    slug: "foreign-settlement",
    categorySlug: "wealth",
    shortDescription: "Relocation and abroad-life storytelling from chart travel themes.",
    reportTemplateKey: "foreign-settlement",
    sortOrder: 4,
  },
  {
    name: "Education Analysis",
    slug: "education-analysis",
    categorySlug: "wealth",
    shortDescription: "Learning style and study motivation notes from the 5th house.",
    reportTemplateKey: "education-analysis",
    sortOrder: 5,
  },
  {
    name: "Family Analysis",
    slug: "family-analysis",
    categorySlug: "wealth",
    shortDescription: "Family bond themes and household dynamics from chart symbolism.",
    reportTemplateKey: "family-analysis",
    sortOrder: 6,
  },
  {
    name: "Children Analysis",
    slug: "children-analysis",
    categorySlug: "wealth",
    shortDescription: "Parenting and children motifs for gentle, reflective storytelling.",
    reportTemplateKey: "children-analysis",
    sortOrder: 7,
  },
  {
    name: "Life Path Analysis",
    slug: "life-path-analysis",
    categorySlug: "wealth",
    shortDescription: "Big-picture life journey themes from lagna, Sun, and 9th-house cues.",
    reportTemplateKey: "life-path-analysis",
    sortOrder: 8,
  },
  {
    name: "Major Life Events Analysis",
    slug: "major-life-events-analysis",
    categorySlug: "wealth",
    shortDescription: "Symbolic markers for chapters like moves, milestones, and fresh starts.",
    reportTemplateKey: "major-life-events-analysis",
    sortOrder: 9,
  },
  {
    name: "Complete Life Report",
    slug: "complete-life-report",
    categorySlug: "wealth",
    shortDescription: "Wide-angle life narrative blending key houses, dasha, and transits.",
    reportTemplateKey: "complete-life-report",
    sortOrder: 10,
  },

  // Dosha & Planets (10)
  {
    name: "Dosha Analysis",
    slug: "dosha-analysis",
    categorySlug: "dosha",
    shortDescription: "Combined dosha scan explained in plain, curiosity-friendly language.",
    reportTemplateKey: "dosha-analysis",
    sortOrder: 1,
  },
  {
    name: "Rahu-Ketu Analysis",
    slug: "rahu-ketu-analysis",
    categorySlug: "dosha",
    shortDescription: "North and south node themes about cravings, detours, and growth edges.",
    reportTemplateKey: "rahu-ketu-analysis",
    sortOrder: 2,
  },
  {
    name: "Saturn Analysis",
    slug: "saturn-analysis",
    categorySlug: "dosha",
    shortDescription: "Shani symbolism around discipline, patience, and life lessons.",
    reportTemplateKey: "saturn-analysis",
    sortOrder: 3,
  },
  {
    name: "Sade Sati Report",
    slug: "sade-sati-report",
    categorySlug: "dosha",
    shortDescription: "Sade sati phase status with calm transit storytelling.",
    reportTemplateKey: "sade-sati-report",
    sortOrder: 4,
  },
  {
    name: "Jupiter Analysis",
    slug: "jupiter-analysis",
    categorySlug: "dosha",
    shortDescription: "Guru themes of wisdom, optimism, and expansive life chapters.",
    reportTemplateKey: "jupiter-analysis",
    sortOrder: 5,
  },
  {
    name: "Mars Analysis",
    slug: "mars-analysis",
    categorySlug: "dosha",
    shortDescription: "Mangal energy notes on drive, courage, and spirited momentum.",
    reportTemplateKey: "mars-analysis",
    sortOrder: 6,
  },
  {
    name: "Venus Analysis",
    slug: "venus-analysis",
    categorySlug: "dosha",
    shortDescription: "Shukra motifs about charm, creativity, comfort, and affection.",
    reportTemplateKey: "venus-analysis",
    sortOrder: 7,
  },
  {
    name: "Mercury Analysis",
    slug: "mercury-analysis",
    categorySlug: "dosha",
    shortDescription: "Budh themes on communication flair, wit, and mental agility.",
    reportTemplateKey: "mercury-analysis",
    sortOrder: 8,
  },
  {
    name: "Sun Analysis",
    slug: "sun-analysis",
    categorySlug: "dosha",
    shortDescription: "Surya symbolism about confidence, visibility, and core identity.",
    reportTemplateKey: "sun-analysis",
    sortOrder: 9,
  },
  {
    name: "Moon Analysis",
    slug: "moon-analysis",
    categorySlug: "dosha",
    shortDescription: "Chandra themes on emotions, intuition, and inner comfort needs.",
    reportTemplateKey: "moon-analysis",
    sortOrder: 10,
  },

  // Self Discovery (10)
  {
    name: "AI Face Self-Discovery",
    slug: "ai-face-self-discovery",
    categorySlug: "self-discovery",
    shortDescription: "Playful AI face scan that turns features into personality story prompts.",
    reportTemplateKey: "ai-face-self-discovery",
    sortOrder: 1,
  },
  {
    name: "Face Personality Interpretation",
    slug: "face-personality-interpretation",
    categorySlug: "self-discovery",
    shortDescription: "Face-reading style notes on temperament—for fun self-reflection only.",
    reportTemplateKey: "face-personality-interpretation",
    sortOrder: 2,
  },
  {
    name: "Face Feature Interpretation",
    slug: "face-feature-interpretation",
    categorySlug: "self-discovery",
    shortDescription: "Feature-by-feature symbolic meanings from classic physiognomy lore.",
    reportTemplateKey: "face-feature-interpretation",
    sortOrder: 3,
  },
  {
    name: "Communication Style Analysis",
    slug: "communication-style-analysis",
    categorySlug: "self-discovery",
    shortDescription: "How you may come across in conversation, based on face and chart cues.",
    reportTemplateKey: "communication-style-analysis",
    sortOrder: 4,
  },
  {
    name: "Leadership Style Analysis (Face)",
    slug: "face-leadership-style-analysis",
    categorySlug: "self-discovery",
    shortDescription: "Face-led leadership presence themes for entertainment and self-awareness.",
    reportTemplateKey: "face-leadership-style-analysis",
    sortOrder: 5,
  },
  {
    name: "Career Style Analysis",
    slug: "career-style-analysis",
    categorySlug: "self-discovery",
    shortDescription: "Work persona motifs blending face reading with symbolic career flair.",
    reportTemplateKey: "career-style-analysis",
    sortOrder: 6,
  },
  {
    name: "Relationship Style Analysis",
    slug: "relationship-style-analysis",
    categorySlug: "self-discovery",
    shortDescription: "Affection and attachment style storytelling from expressive face cues.",
    reportTemplateKey: "relationship-style-analysis",
    sortOrder: 7,
  },
  {
    name: "Strengths & Growth Analysis",
    slug: "strengths-growth-analysis",
    categorySlug: "self-discovery",
    shortDescription: "Balanced strengths and growth edges for mindful personal reflection.",
    reportTemplateKey: "strengths-growth-analysis",
    sortOrder: 8,
  },
  {
    name: "Self-Discovery Face Report",
    slug: "self-discovery-face-report",
    categorySlug: "self-discovery",
    shortDescription: "Full face-reading PDF blending personality, style, and growth chapters.",
    reportTemplateKey: "self-discovery-face-report",
    sortOrder: 9,
  },
  {
    name: "Premium Face Reading",
    slug: "premium-face-reading",
    categorySlug: "self-discovery",
    shortDescription: "Deluxe face report with richer chapters and shareable PDF delivery.",
    reportTemplateKey: "premium-face-reading",
    sortOrder: 10,
  },

  // Numerology (10)
  {
    name: "Life Path Number",
    slug: "life-path-number",
    categorySlug: "numerology",
    shortDescription: "Birth-date life path number with symbolic personality storytelling.",
    reportTemplateKey: "life-path-number",
    sortOrder: 1,
  },
  {
    name: "Destiny Number",
    slug: "destiny-number",
    categorySlug: "numerology",
    shortDescription: "Name-based destiny number themes for playful self-discovery.",
    reportTemplateKey: "destiny-number",
    sortOrder: 2,
  },
  {
    name: "Soul Urge Number",
    slug: "soul-urge-number",
    categorySlug: "numerology",
    shortDescription: "Inner motivation number notes about what quietly inspires you.",
    reportTemplateKey: "soul-urge-number",
    sortOrder: 3,
  },
  {
    name: "Personality Number",
    slug: "personality-number",
    categorySlug: "numerology",
    shortDescription: "Outer-persona number themes about first impressions and social vibe.",
    reportTemplateKey: "personality-number",
    sortOrder: 4,
  },
  {
    name: "Name Numerology",
    slug: "name-numerology",
    categorySlug: "numerology",
    shortDescription: "Full-name numerology breakdown with light interpretive notes.",
    reportTemplateKey: "name-numerology",
    sortOrder: 5,
  },
  {
    name: "Business Name Numerology",
    slug: "business-name-numerology",
    categorySlug: "numerology",
    shortDescription: "Brand-name number vibes for founders who enjoy symbolic naming fun.",
    reportTemplateKey: "business-name-numerology",
    sortOrder: 6,
  },
  {
    name: "Mobile Number Numerology",
    slug: "mobile-number-numerology",
    categorySlug: "numerology",
    shortDescription: "Phone-number numerology reading presented as entertainment.",
    reportTemplateKey: "mobile-number-numerology",
    sortOrder: 7,
  },
  {
    name: "Numerology Compatibility",
    slug: "numerology-compatibility",
    categorySlug: "numerology",
    shortDescription: "Number-match chemistry between two names or birth dates.",
    reportTemplateKey: "numerology-compatibility",
    sortOrder: 8,
  },
  {
    name: "Personal Year Report",
    slug: "personal-year-report",
    categorySlug: "numerology",
    shortDescription: "Current personal year themes for reflective planning and curiosity.",
    reportTemplateKey: "personal-year-report",
    sortOrder: 9,
  },
  {
    name: "Complete Numerology Report",
    slug: "complete-numerology-report",
    categorySlug: "numerology",
    shortDescription: "All core numbers in one PDF for number-lovers and gift givers.",
    reportTemplateKey: "complete-numerology-report",
    sortOrder: 10,
  },

  // Daily Astrology (8)
  {
    name: "Daily Horoscope",
    slug: "daily-horoscope",
    categorySlug: "daily-astrology",
    shortDescription: "Today's symbolic horoscope prompts for your sign or chart.",
    reportTemplateKey: "daily-horoscope",
    sortOrder: 1,
  },
  {
    name: "Weekly Horoscope",
    slug: "weekly-horoscope",
    categorySlug: "daily-astrology",
    shortDescription: "Seven-day rashifal-style themes for mood and momentum reflection.",
    reportTemplateKey: "weekly-horoscope",
    sortOrder: 2,
  },
  {
    name: "Monthly Horoscope",
    slug: "monthly-horoscope",
    categorySlug: "daily-astrology",
    shortDescription: "Month-ahead transit storytelling for gentle planning inspiration.",
    reportTemplateKey: "monthly-horoscope",
    sortOrder: 3,
  },
  {
    name: "Yearly Horoscope",
    slug: "yearly-horoscope",
    categorySlug: "daily-astrology",
    shortDescription: "Annual rashifal overview with chapter themes for the year ahead.",
    reportTemplateKey: "yearly-horoscope",
    sortOrder: 4,
  },
  {
    name: "Personalized Daily Guidance",
    slug: "personalized-daily-guidance",
    categorySlug: "daily-astrology",
    shortDescription: "Chart-aware daily nudges tailored to your birth details.",
    reportTemplateKey: "personalized-daily-guidance",
    sortOrder: 5,
  },
  {
    name: "Planetary Transit Report",
    slug: "planetary-transit-report",
    categorySlug: "daily-astrology",
    shortDescription: "Gochar highlights when major planets shift signs or houses.",
    reportTemplateKey: "planetary-transit-report",
    sortOrder: 6,
  },
  {
    name: "Personalized Monthly Guidance",
    slug: "personalized-monthly-guidance",
    categorySlug: "daily-astrology",
    shortDescription: "Personalized month-ahead notes keyed to your unique chart.",
    reportTemplateKey: "personalized-monthly-guidance",
    sortOrder: 7,
  },
  {
    name: "Annual Life Forecast",
    slug: "annual-life-forecast",
    categorySlug: "daily-astrology",
    shortDescription: "Birthday-to-birthday year-ahead forecast for reflective journaling.",
    reportTemplateKey: "annual-life-forecast",
    sortOrder: 8,
  },
];

export const MEMBERSHIP_PRODUCT = {
  name: "Complete Self Discovery Membership",
  slug: "complete-self-discovery-membership",
  categorySlug: "self-discovery",
  shortDescription:
    "Annual membership with access to self-discovery reports, daily alerts, and member pricing.",
  description:
    "Unlock the full self-discovery catalog, daily horoscope alerts, and member benefits for one year.",
  membershipPriceYearly: 2999,
  reportTemplateKey: "membership-self-discovery",
  sortOrder: 0,
};

export const SYSTEM_SETTINGS = [
  { key: "brand.name", value: "JyotishKundali", group: "brand", label: "Brand name" },
  { key: "brand.tagline", value: "Know Yourself. Understand Your Path.", group: "brand", label: "Tagline" },
  { key: "brand.domain", value: "jyotishkundali.com", group: "brand", label: "Primary domain" },
  { key: "brand.support_email", value: "support@jyotishkundali.com", group: "brand", label: "Support email" },
  { key: "brand.support_phone", value: "+91-0000000000", group: "brand", label: "Support phone" },
  { key: "commerce.currency", value: "INR", group: "commerce", label: "Default currency" },
  { key: "commerce.default_report_price", value: 499, group: "commerce", label: "Default report price (INR)" },
  { key: "commerce.membership_yearly_price", value: 2999, group: "commerce", label: "Membership yearly price (INR)" },
  { key: "reports.delivery_note", value: "PDF delivered within minutes after payment.", group: "reports", label: "Default delivery note" },
  { key: "reports.default_language", value: "en", group: "reports", label: "Default report language" },
  { key: "reports.languages_available", value: ["en", "hi"], group: "reports", label: "Available report languages" },
  { key: "astrology.ayanamsa", value: "lahiri", group: "astrology", label: "Default ayanamsa" },
  { key: "astrology.house_system", value: "whole_sign", group: "astrology", label: "Default house system" },
] as const;
